# Nixpacks configuration for Railway
# Forces Python 3.11 for rembg compatibility

[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
